# Site settings
title: BuilAPK
name: APK
email: build@buildapk.com
description: > # this means to ignore newlines until "baseurl:"
  来嘛，编译一下。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://buildapk.com" # the base hostname & protocol for your site

timezone: Asia/Shanghai

# sns
author: fire
twitter_username: micneer
github_username:  micneer

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Pages
paginate: 30
paginate_path: "p:num"

# Permalink
highlighter: rouge
permalink: /:categories/:title.html
