# Site settings
title: BuilAPK
name: APK
email: build@buildapk.com
description: > # this means to ignore newlines until "baseurl:"
  编译一下，你就知道。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://buildapk.com" # the base hostname & protocol for your site

timezone: Asia/Shanghai

# sns
author: fire
twitter_username: micneer
github_username:  micneer

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout 
  - jekyll-titles-from-headings

# Pages
paginate: 30
paginate_path: "p:num"

# Permalink
highlighter: rouge
permalink: /:categories/:title.html
